<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_ADS" Id="{ab53a300-a8c7-4757-a8eb-e10b4abda9ef}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ADS
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
     fbLogger : FB_LogMessage := (eSubsystem:=E_SubSystem.FIELDBUS);
    tErrorPresent : R_TRIG;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>