<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_Pump" Id="{00c4f02d-0992-44f0-9021-57d8126c2097}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Pump
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	
 // For logging
    fbLogger : FB_LogMessage := (eSubsystem:=E_SubSystem.VACUUM);
    ePrevState : E_PumpState;
    tErrorPresent : R_TRIG;
    tAction : R_TRIG; // Primary action of this device (OPN_DO, PUMP_RUN, etc.)	
	tFault : F_TRIG;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Action Name="ACT_Logger" Id="{3638f3f4-c294-44fa-a1a7-c4bfc15b56a5}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="FB_Pump">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Pump.ACT_Logger">
      <LineId Id="22" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>