<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_Gauge" Id="{7a1f28cc-0783-4ebe-9457-6569085eece6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Gauge
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR

// For logging
    fbLogger : FB_LogMessage := (eSubsystem:=E_SubSystem.VACUUM);
    ePrevState : E_PressureState;
    tErrorPresent : R_TRIG;
    tAction : R_TRIG; // Primary action of this device (OPN_DO, etc.)
    tOverrideActivated : R_TRIG;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>