<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FB_Gauge" Id="{4c6deb7b-3c2b-4af3-9c7f-b9d7e9e5a802}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Gauge
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Gauge">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>